/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppServiceRouteImport } from './routes/app.service'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppOwnerRouteImport } from './routes/app.owner'
import { Route as AppObjectsRouteImport } from './routes/app.objects'
import { Route as AppInstallmentsRouteImport } from './routes/app.installments'
import { Route as AppInstallationsRouteImport } from './routes/app.installations'
import { Route as AppHylaRouteImport } from './routes/app.hyla'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDealsRouteImport } from './routes/app.deals'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCoordinatorRouteImport } from './routes/app.coordinator'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCallsRouteImport } from './routes/app.calls'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppObjectsRoute = AppObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallmentsRoute = AppInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallationsRoute = AppInstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => AppRoute,
} as any)
const AppHylaRoute = AppHylaRouteImport.update({
  id: '/hyla',
  path: '/hyla',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoordinatorRoute = AppCoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/calls': typeof AppCallsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/coordinator': typeof AppCoordinatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deals': typeof AppDealsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hyla': typeof AppHylaRoute
  '/app/installations': typeof AppInstallationsRoute
  '/app/installments': typeof AppInstallmentsRoute
  '/app/objects': typeof AppObjectsRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/products': typeof AppProductsRoute
  '/app/service': typeof AppServiceRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/calls': typeof AppCallsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/coordinator': typeof AppCoordinatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deals': typeof AppDealsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hyla': typeof AppHylaRoute
  '/app/installations': typeof AppInstallationsRoute
  '/app/installments': typeof AppInstallmentsRoute
  '/app/objects': typeof AppObjectsRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/products': typeof AppProductsRoute
  '/app/service': typeof AppServiceRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/calls': typeof AppCallsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/coordinator': typeof AppCoordinatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deals': typeof AppDealsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hyla': typeof AppHylaRoute
  '/app/installations': typeof AppInstallationsRoute
  '/app/installments': typeof AppInstallmentsRoute
  '/app/objects': typeof AppObjectsRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/products': typeof AppProductsRoute
  '/app/service': typeof AppServiceRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/calls'
    | '/app/clients'
    | '/app/coordinator'
    | '/app/dashboard'
    | '/app/deals'
    | '/app/finance'
    | '/app/hyla'
    | '/app/installations'
    | '/app/installments'
    | '/app/objects'
    | '/app/owner'
    | '/app/products'
    | '/app/service'
    | '/app/tasks'
    | '/app/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/calls'
    | '/app/clients'
    | '/app/coordinator'
    | '/app/dashboard'
    | '/app/deals'
    | '/app/finance'
    | '/app/hyla'
    | '/app/installations'
    | '/app/installments'
    | '/app/objects'
    | '/app/owner'
    | '/app/products'
    | '/app/service'
    | '/app/tasks'
    | '/app/team'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/calls'
    | '/app/clients'
    | '/app/coordinator'
    | '/app/dashboard'
    | '/app/deals'
    | '/app/finance'
    | '/app/hyla'
    | '/app/installations'
    | '/app/installments'
    | '/app/objects'
    | '/app/owner'
    | '/app/products'
    | '/app/service'
    | '/app/tasks'
    | '/app/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/service': {
      id: '/app/service'
      path: '/service'
      fullPath: '/app/service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owner': {
      id: '/app/owner'
      path: '/owner'
      fullPath: '/app/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/objects': {
      id: '/app/objects'
      path: '/objects'
      fullPath: '/app/objects'
      preLoaderRoute: typeof AppObjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/installments': {
      id: '/app/installments'
      path: '/installments'
      fullPath: '/app/installments'
      preLoaderRoute: typeof AppInstallmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/installations': {
      id: '/app/installations'
      path: '/installations'
      fullPath: '/app/installations'
      preLoaderRoute: typeof AppInstallationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hyla': {
      id: '/app/hyla'
      path: '/hyla'
      fullPath: '/app/hyla'
      preLoaderRoute: typeof AppHylaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deals': {
      id: '/app/deals'
      path: '/deals'
      fullPath: '/app/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coordinator': {
      id: '/app/coordinator'
      path: '/coordinator'
      fullPath: '/app/coordinator'
      preLoaderRoute: typeof AppCoordinatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls': {
      id: '/app/calls'
      path: '/calls'
      fullPath: '/app/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCallsRoute: typeof AppCallsRoute
  AppClientsRoute: typeof AppClientsRoute
  AppCoordinatorRoute: typeof AppCoordinatorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDealsRoute: typeof AppDealsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppHylaRoute: typeof AppHylaRoute
  AppInstallationsRoute: typeof AppInstallationsRoute
  AppInstallmentsRoute: typeof AppInstallmentsRoute
  AppObjectsRoute: typeof AppObjectsRoute
  AppOwnerRoute: typeof AppOwnerRoute
  AppProductsRoute: typeof AppProductsRoute
  AppServiceRoute: typeof AppServiceRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallsRoute: AppCallsRoute,
  AppClientsRoute: AppClientsRoute,
  AppCoordinatorRoute: AppCoordinatorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDealsRoute: AppDealsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppHylaRoute: AppHylaRoute,
  AppInstallationsRoute: AppInstallationsRoute,
  AppInstallmentsRoute: AppInstallmentsRoute,
  AppObjectsRoute: AppObjectsRoute,
  AppOwnerRoute: AppOwnerRoute,
  AppProductsRoute: AppProductsRoute,
  AppServiceRoute: AppServiceRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
